### ISSUE TITLE
NPE during OAuthGetTemporaryToken

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#110]
```
Version: google-api-client-1.2.2-alpha
Environment: Android

When attempting to dance with LoVEFILM, I'm getting the following:

FATAL EXCEPTION: IntentService[AuthorizationService]
java.lang.NullPointerException
    at com.google.api.client.http.UrlEncodedParser.parse(UrlEncodedParser.java:139)
    at com.google.api.client.auth.oauth.AbstractOAuthGetToken.execute(AbstractOAuthGetToken.java:67)
    at com.ctoforaday.livefilm.AuthorizationService.onHandleIntent(AuthorizationService.java:40)
    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:123)
    at android.os.HandlerThread.run(HandlerThread.java:60)

Now, I can't tell what it's doing yet, but it definitely shouldn't be doing 
that.  It suggests that, while parsing, the map is null.
```

Original issue reported on code.google.com by `gblock@google.com` on 3 Feb 2011 at 8:57
- Merged into: #111

**Comment by GoogleCodeExporter** [comment]
```
Sorry, the OAuth 2 implementation is broken in 1.2.2-alpha.  It should be fixed 
with 1.3 which hasn't released yet.  Sorry about that.
```

Original comment by `yan...@google.com` on 3 Feb 2011 at 9:21
- Changed state: **Fixed**
- Added labels: **Milestone-Version1.3.0**

**Comment by GoogleCodeExporter** [comment]
```
Issue 111 has been merged into this issue.
```

Original comment by `yan...@google.com` on 3 Feb 2011 at 9:22

**Comment by GoogleCodeExporter** [comment]
```
Perhaps, but this is OAuth 1.0a we're talking about here.  :)

Any chance of fixing it by adding the map interface to the temporary token 
response?  I'll try building a jar against head when I get home.
```

Original comment by `gblock@google.com` on 4 Feb 2011 at 2:26

**Comment by GoogleCodeExporter** [comment]
```
You are right. Reopening issue 111.
```

Original comment by `yan...@google.com` on 4 Feb 2011 at 2:59

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 18 Feb 2011 at 1:27
- Changed state: **Duplicate**
- Removed labels: **Milestone-Version1.3.0**
