### ISSUE TITLE
AccessControlException thrown when running on Google App Engine

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#12]
```
Version of google-api-java-client (e.g. 1.1.0-alpha)?

1.1.0-alpha

Java environment (e.g. Android 2.2, App Engine 1.3.7, Java 6 on Windows)?

App Engine 1.3.7

What steps will reproduce the problem?
1. Start program

What is the expected output?

No exception.

What do you see instead?

Caused by: java.security.AccessControlException: access denied 
(java.lang.RuntimePermission setFactory)
    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:342)
    at java.security.AccessController.checkPermission(AccessController.java:553)
    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
    at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:166)
    at java.lang.SecurityManager.checkSetFactory(SecurityManager.java:1629)
    at java.net.HttpURLConnection.setFollowRedirects(HttpURLConnection.java:267)
    at com.google.api.client.javanet.NetHttpTransport.<clinit>(NetHttpTransport.java:36)

Please provide any additional information below.

Was working in version 1.1.0-alpha.
```

Original issue reported on code.google.com by `yan...@google.com` on 13 Sep 2010 at 8:22

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 14 Sep 2010 at 1:21
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 14 Sep 2010 at 1:35
- Added labels: **Priority-Critical**
- Removed labels: **Priority-High**

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 8 Jan 2011 at 6:39
- Added labels: **Component-Google-AppEngine**
