### ISSUE TITLE
AbstractAtomFeedParser causes NullPointerException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#314]
```
version 1.5.0-beta

Describe the problem.

parseNextEntry method is passing null into Xml.parseElement(); when feedParsed 
is false, instead of destination object, which causes NPE in 
context.add(destination.getClass());

  public Object parseNextEntry() throws IOException, XmlPullParserException {
    if (!feedParsed) {
      feedParsed = true;
      Xml.parseElement(parser, null, namespaceDictionary, Atom.StopAtAtomEntry.INSTANCE);
    }

java.lang.NullPointerException
    at com.google.api.client.xml.Xml.parseElement(Xml.java:202)
    at com.google.api.client.xml.atom.AbstractAtomFeedParser.parseNextEntry(AbstractAtomFeedParser.java:170)
    at com.google.api.client.http.xml.atom.AtomFeedParser.parseNextEntry(AtomFeedParser.java:79)


How would you expect it to be fixed?

Well I don't see a reason why the feed should be parsed before, why not just 
having parsing method that retrieves feed entries ?
```

Original issue reported on code.google.com by `liska.jakub` on 7 Oct 2011 at 11:13

**Comment by GoogleCodeExporter** [comment]
Original comment by `rmis...@google.com` on 14 Jan 2013 at 3:31

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 14 Jan 2013 at 4:08
- Added labels: **Component-XML**
