### ISSUE TITLE
IllegalArgumentException: HTTP transport doesn't support PATCH

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#398]
```

Stack trace:

Exception in thread "main" java.lang.IllegalArgumentException: HTTP transport 
doesn't support PATCH
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:88)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:649)
    at com.google.api.client.http.json.JsonHttpClient.executeUnparsed(JsonHttpClient.java:292)
    at com.google.api.client.http.json.JsonHttpRequest.executeUnparsed(JsonHttpRequest.java:106)
    at com.google.api.services.calendar.Calendar$Events$Patch.execute(Calendar.java:2684)


Looks like it happens because GoogleClient overrides the deprecated 
buildHttpRequest from JsonHttpClient.

```

Original issue reported on code.google.com by `rmis...@google.com` on 24 Jan 2012 at 10:02

**Comment by GoogleCodeExporter** [comment]
Original comment by `rmis...@google.com` on 24 Jan 2012 at 10:06
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Reported by aalbert.
```

Original comment by `rmis...@google.com` on 24 Jan 2012 at 10:08

**Comment by GoogleCodeExporter** [comment]
```
http://codereview.appspot.com/5575058/
```

Original comment by `rmis...@google.com` on 25 Jan 2012 at 7:17
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 12 Mar 2012 at 8:34
- Added labels: **Priority-Medium**
- Removed labels: **Priority-High**
