### ISSUE TITLE
Google Affiliate Network API

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#476]
```
Which Google API and version (e.g. Google Calendar Data API version 2)?

Google Affiliate Network API V1 Beta 1

What format (e.g. JSON, Atom)?

JSON

What Authentation (e.g. OAuth, OAuth 2, ClientLogin)?

OAuth 2

Java environment (e.g. Java 6, Android 2.3, App Engine)?

Java

External references, such as API reference guide?

https://developers.google.com/affiliate-network/

Please provide any additional information below.

I have always a 500 Internal Server Error, check my test in attachment.
```

Original issue reported on code.google.com by `francis....@gmail.com` on 1 May 2012 at 5:17

Attachments:
- [GANTest.java](https://storage.googleapis.com/google-code-attachments/google-api-java-client/issue-476/comment-0/GANTest.java)

**Comment by GoogleCodeExporter** [comment]
```
Reponse:

Exception in thread "main" 
com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal 
Server Error
{
  "code" : 500,
  "message" : null
}
    at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:159)
    at com.google.api.client.googleapis.json.GoogleJsonResponseException.execute(GoogleJsonResponseException.java:187)
    at com.google.api.client.googleapis.services.GoogleClient.executeUnparsed(GoogleClient.java:115)
    at com.google.api.client.http.json.JsonHttpRequest.executeUnparsed(JsonHttpRequest.java:112)
    at com.google.api.services.gan.Gan$Advertisers$List.execute(Gan.java:192)
    at Test.main(Test.java:47)
```

Original comment by `francis....@gmail.com` on 1 May 2012 at 5:17

**Comment by GoogleCodeExporter** [comment]
Original comment by `rmis...@google.com` on 14 Jan 2013 at 3:31
