### ISSUE TITLE
 Resumable upload fails when writing multiple chunks.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#521]
```
Reported by internal user:

Writing large amounts of data via resumable upload fails with:

java.io.IOException: insufficient data written
       at sun.net.www.protocol.http.HttpURLConnection.close(HttpURLConnection.java:2743)
       at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:83)
       at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:845)
       at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:251)
       at com.google.api.services.storage.Storage.executeUnparsed(Storage.java:1754)
       at com.google.api.services.storage.Storage.execute(Storage.java:1776)

Which is actually caused by writing too much data when uploading a chunk. This 
started breaking on 5/24 as a result of a change which removed limiting the 
data copied and did not change 
MediaHttpUploader#setContentAndHeadersOnCurrentRequest to use a 
LimitInputStream.
```

Original issue reported on code.google.com by `rmis...@google.com` on 14 Jun 2012 at 8:02

**Comment by GoogleCodeExporter** [comment]
Original comment by `rmis...@google.com` on 14 Jun 2012 at 8:02
- Added labels: **Milestone-Version1.10.2**

**Comment by GoogleCodeExporter** [comment]
```
http://codereview.appspot.com/6294073/
```

Original comment by `rmis...@google.com` on 15 Jun 2012 at 2:50
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I'm sometimes getting a similar error while uploading a file. Is this the same 
error?
I'm using version v2-rev13-1.8.0-beta 
```

Original comment by `david.va...@gmail.com` on 13 Feb 2013 at 10:14

Attachments:
- [googleDriveError.txt](https://storage.googleapis.com/google-code-attachments/google-api-java-client/issue-521/comment-3/googleDriveError.txt)

**Comment by GoogleCodeExporter** [comment]
```
Yes looks like the same error, it should go away if you use the latest version 
of the library.
```

Original comment by `rmis...@google.com` on 13 Feb 2013 at 12:04
