### ISSUE TITLE
MediaHttpUploader.upload() requires a known InputStreamContent size

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#591]
```
Version of google-api-java-client (e.g. 1.5.0-beta)?
1.10.3-beta

Java environment (e.g. Java 6, Android 2.3, App Engine)?
Java 6

Describe the problem.
If you provide an InputStreamContent where you've not specified setLength(), 
and thus it defaults to -1 (unknown length), you get a precondition failed:

java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:72)
    at com.google.api.client.googleapis.media.MediaHttpUploader.getMediaContentLength(MediaHttpUploader.java:315)
    at com.google.api.client.googleapis.media.MediaHttpUploader.executeUploadInitiation(MediaHttpUploader.java:333)
    at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:252)


How would you expect it to be fixed?
1) MediaHttpUploader.getMediaContentLength() should remove the precondition.
2) MediaHttpUploader.executeUploadInitiation should 
setUploadContentLength(null) (or if omitting that header doesn't work, there 
should be an overload that allows a "X-Upload-Content-Length: *", which is how 
you specify an unknown length to the upload service).
3) MediaHttpUploader.setContentAndHeadersOnCurrentRequest should specify the 
Content-Range ending in * when getMediaContentLength() == -1. It also needs to 
change its blockSize calculation in the case getMediaContentLength() == -1 to 
try to read the whole block and if you reach the end of the stream, 
setMediaContentLength() to be the appropriate value.
4) I'm not sure this is required, but you may end up having to additionally add 
X-Upload-Content-Length: * in the setContentAndHeadersOnCurrentRequest until 
such time as you resolve the end of the stream. 
```

Original issue reported on code.google.com by `nherr...@google.com` on 16 Aug 2012 at 5:17

**Comment by GoogleCodeExporter** [comment]
```
Example from nherring:

Content-Range: 0-99/*
Content-Range: 100-199/*
Content-Range: 199-250/250

He also mentioned that mikeyu will be able to provide more information about 
this if required.
```

Original comment by `rmis...@google.com` on 16 Aug 2012 at 5:22

**Comment by GoogleCodeExporter** [comment]
Original comment by `rmis...@google.com` on 16 Aug 2012 at 5:23
- Added labels: **Milestone-Version1.12.0**

**Comment by GoogleCodeExporter** [comment]
```
From the documentation, you can omit X-Upload-Content-Length if the size is 
unknown at the time of resumable session creation.

It does not appear to me that you can actually pass in null for 
setUploadContentLength, despite the commentary, and that this may require a 
change to GoogleHeaders.java to make the uploadContentLength be a Long rather 
than a long.
```

Original comment by `nherr...@google.com` on 16 Aug 2012 at 5:37

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 20 Aug 2012 at 12:15
- Changed state: **Accepted**
- Added labels: **Priority-High**, **Component-Media**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 20 Aug 2012 at 12:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 20 Aug 2012 at 12:15
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 8 Oct 2012 at 7:18
- Added labels: **Milestone-Version1.13.0**
- Removed labels: **Milestone-Version1.12.0**

**Comment by GoogleCodeExporter** [comment]
```
https://codereview.appspot.com/6852066/
```

Original comment by `rmis...@google.com` on 5 Dec 2012 at 4:44
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `rmis...@google.com` on 10 Dec 2012 at 2:19
- Changed state: **Fixed**
