### ISSUE TITLE
the classpath entry of the google-api-services-calendar's manifest is wrong

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#642]
```
Version of google-api-java-client (e.g. 1.5.0-beta)?
google-api-client-1.11.0-beta.jar 
google-api-services-calendar-v3-rev16-1.8.0-beta.jar 

Java environment (e.g. Java 6, Android 2.3, App Engine)?
JAVA 6

I'm trying to import the google api calendar by maven into my project. However, 
when I'm trying to deploy in a JAVAEE container like jboss as7, I have a 
classloading error caused by the content of the manifest file of 
google-api-services-calendar-v3-rev16-1.8.0-beta.jar 

An example :

Caused by: java.io.FileNotFoundException: 
\home\codegen\dependencies\java\stable\dependencies\libs\google-http-client-1.11
.0-beta.jar (Le chemin d'accès spécifié est introuvable)
    at java.util.zip.ZipFile.open(Native Method) [rt.jar:1.6.0_23]
    at java.util.zip.ZipFile.<init>(ZipFile.java:127) [rt.jar:1.6.0_23]
    at java.util.jar.JarFile.<init>(JarFile.java:135) [rt.jar:1.6.0_23]
    at java.util.jar.JarFile.<init>(JarFile.java:99) [rt.jar:1.6.0_23]
    at org.jboss.as.server.moduleservice.ExternalModuleSpecService.start(ExternalModuleSpecService.java:63) [jboss-as-server-7.1.1.Final.jar:7.1.1.Final]
    ... 5 more


As you can see below, the classpath contain absolute paths and not relative 
paths. 

Class-Path:  
/home/codegen/dependencies/java/stable/dependencies/libs/google-api-client-1.11.
0-beta.jar 
/home/codegen/dependenciesjava/stable/dependencies/libs/google-oauth-client-1.11
.0-beta.jar 
/home/codegen/dependencies/java/stable/dependencieslibs/google-http-client-1.11.
0-beta.jar 
/home/codegen/dependencies/java/stable/dependencies/libs/guava-11.0.1.jar

Such as it is, this artifact is not deployable by the maven way.

It would be nice to deploy an another release of this artifact with a correct 
manifest content.


```

Original issue reported on code.google.com by `alexan...@touret.info` on 24 Oct 2012 at 7:35

**Comment by GoogleCodeExporter** [comment]
```
Hi Jacob,

I do not see the manifest logic in apiserving/libgen/gen/java/... where are 
these paths calculated?

Thanks!
```

Original comment by `rmis...@google.com` on 24 Oct 2012 at 11:15

**Comment by GoogleCodeExporter** [comment]
```
The manifest is created in the compilation state, so either by maven or on 
bigcluster with GenerateJavaBinary.sh.  I'm removing the class-path entry from 
the manifest for the latter, and Yaniv is doing the same for the former.
```

Original comment by `smull...@google.com` on 24 Oct 2012 at 2:28

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 24 Oct 2012 at 4:07
- Changed state: **Accepted**
- Added labels: **Priority-High**, **Milestone-CodeGenVersion1.9.0**, **Component-Google-APIs**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Is there any roadmap for this release (1.9.0) ?
```

Original comment by `alexan...@touret.info` on 24 Oct 2012 at 7:58

**Comment by GoogleCodeExporter** [comment]
```
we're hoping to release this very soon, maybe within a week.
```

Original comment by `yan...@google.com` on 29 Oct 2012 at 7:21
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `yan...@google.com` on 29 Oct 2012 at 7:24
- Added labels: **Milestone-Version1.12.0**
- Removed labels: **Milestone-CodeGenVersion1.9.0**
