### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: com.google.api.client.http.HttpHeaders.setAuthorization(Ljava/lang/String;

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#752]
```
Version of google-api-java-client (e.g. 1.5.0-beta)?


Java environment (e.g. Java 6, Android 2.3, App Engine)?

 Java 6
Describe the problem.
Exception in thread "main" java.lang.NoSuchMethodError: 
com.google.api.client.http.HttpHeaders.setAuthorization(Ljava/lang/String;)V
    at com.google.api.client.auth.oauth2.draft10.AccessProtectedResource.intercept(AccessProtectedResource.java:292)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:888)
    at com.google.sample.UrlShortenerTest.main(UrlShortenerTest.java:68)
Java Result: 1

How would you expect it to be fixed?

```

Original issue reported on code.google.com by `rinu.cha...@gmail.com` on 18 Mar 2013 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
I am using the  UrlShortenerTest  example found in the net

```

Original comment by `rinu.cha...@gmail.com` on 18 Mar 2013 at 11:50
