### ISSUE TITLE
Issue Insufficient data written

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#780]
```
Which Google API and version (e.g. Google Calendar API version 3)?


Java environment (e.g. Java 6, Android 2.3, App Engine)?


External references, such as API reference guide?


Please provide any additional information below.

Hi Team,
we are updated google api to 1.15.0-rc, but we are still getting insufficient 
data written error: what could be the most appropriate chunk size for uploading 
file.
Error:

java.io.IOException: insufficient data written
    at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(Unknown Source)
    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:960)
    at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:482)
    at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:390)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:418)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at WebShortCut.Application.GoogleDrive.GoogleDriveService.uploadFile(GoogleDriveService.java:421)
    at WebShortCut.Application.GoogleDrive.GoogleDriveService.saveFileToDrive(GoogleDriveService.java:142)
    at WebShortCut.Application.GoogleDrive.WebShortCutApp.qUploadFile(WebShortCutApp.java:537)
    at WebShortCut.test.FileUploadTest$RequestFileUpload.run(FileUploadTest.java:75)
    at java.lang.Thread.run(Unknown Source)


```

Original issue reported on code.google.com by `satish.d...@gmail.com` on 16 May 2013 at 10:00

**Comment by GoogleCodeExporter** [comment]
```
can you let me anyone answers
```

Original comment by `satish.d...@gmail.com` on 16 May 2013 at 11:44

**Comment by GoogleCodeExporter** [comment]
```
Hi Can i resume uploads if in between stuck uploading... how give me pls any 
idea 
```

Original comment by `satish.d...@gmail.com` on 16 May 2013 at 12:45
