### ISSUE TITLE
 insufficient data written

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#781]
```
Version of google-api-java-client : 1.15.0-rc


Java environment : jdk-7u17-windows-i586


Describe the problem:

i was using goolge-api-clint 1.10.3-beta and commonly getting this "i.e 
insufficient data witting exception" while uploading files. the chunk size used 
in the application was 10MB.we also changed the chunk size to 256kb/1mb but the 
problem remains the same, then we decided to update the API to 1.15.0-rc. But 
we are still  facing the same problem. This issue is destroying my project.  
Pls help?
 Exception trace: 

java.io.IOException: insufficient data written
    at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(Unknown Source)
    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:960)
    at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:482)
    at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:390)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:418)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at WebShortCut.Application.GoogleDrive.GoogleDriveService.uploadFile(GoogleDriveService.java:715)
    at WebShortCut.Application.GoogleDrive.GoogleDriveService.saveFileToDrive(GoogleDriveService.java:168)
    at WebShortCut.Application.GoogleDrive.WebShortCutApp.qUploadFile(WebShortCutApp.java:537)
    at WebShortCut.test.FileUploadTest$RequestFileUpload.run(FileUploadTest.java:75)
    at java.lang.Thread.run(Unknown Source)  

How would you expect it to be fixed?

```

Original issue reported on code.google.com by `akhi85pr...@gmail.com` on 16 May 2013 at 7:12

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Have the same issue when using java api to stream data into Bigquery. Any clues 
on how to handle it?
```

Original comment by `fionaz...@geotab.com` on 9 Jul 2014 at 6:01
