### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/google-api-java-client#806]
```
Version of google-api-java-client (e.g. 1.15.0-rc)?
1.8.0-beta

Java environment (e.g. Java 6, Android 2.3, App Engine)?
Java 7

Describe the problem.
I'm trying to implement a variation of the GoogleAnalyticsExample.java.
In attachment my own class.
I got the exception that you can see below.
Analytics API responded with an error message: Unrecognized content 
type:application/json;charset=UTF-8
com.google.gdata.util.ParseException: Unrecognized content 
type:application/json;charset=UTF-8
    at com.google.gdata.client.Service.parseResponseData(Service.java:2136)
    at com.google.gdata.client.Service.parseResponseData(Service.java:2098)
    at com.google.gdata.client.Service.getFeed(Service.java:1136)
    at com.google.gdata.client.Service.getFeed(Service.java:998)
    at com.google.gdata.client.GoogleService.getFeed(GoogleService.java:645)
    at com.google.gdata.client.Service.getFeed(Service.java:1017)
    at service.MTXFeed.getAccountFeed(MTXFeed.java:74)
    at service.MTXFeed.main(MTXFeed.java:37)


How would you expect it to be fixed?
I think the default Content Type (application/json;charset=UTF-8) is not 
supported.
```

Original issue reported on code.google.com by `zoe.pe....@gmail.com` on 21 Jun 2013 at 10:25

Attachments:
- [MTXFeed.java](https://storage.googleapis.com/google-code-attachments/google-api-java-client/issue-806/comment-0/MTXFeed.java)

**Comment by GoogleCodeExporter** [comment]
```
Discard the issue. I've found another way to access the profile data.
Thanks.
Regards.
```

Original comment by `zoe.pe....@gmail.com` on 24 Jun 2013 at 10:23

**Comment by GoogleCodeExporter** [comment]
```
Glad to hear you resolved your issue. Please note that version 1.8 of the 
library was released over 14 months ago.  Because numerous bugs have been fixed 
and features added since then, it's recommended you upgrade to the latest 
version of the library. Note that the current stable version of the library is 
a non-beta release candidate, and will soon be followed by our first non-beta 
full release.
```

Original comment by `ngmic...@google.com` on 24 Jun 2013 at 10:27
- Changed state: **Invalid**
